homeassistant:
  name: Irvine Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: 45
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

frontend:

config:

http:
  api_password: !secret api_password

updater:
  include_used_components: true

discovery:

conversation:

history:

logbook:

sun:

tts:
  - platform: google

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - temperature
      - cloud_cover
      - precip_probability
      - summary
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: mqtt
    state_topic: 'njbbaer/multisensor'
    name: 'Multisensor Temperature'
    unit_of_measurement: '°C'
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: 'njbbaer/multisensor'
    name: 'Multisensor Humidity'
    unit_of_measurement: '%'
    value_template: '{{ value_json.humidity }}'

device_tracker:
  - platform: bluetooth_tracker

mqtt:
  broker: test.mosquitto.org

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
